name: CI

on:
  push:
    branches: ["master", "issue_50"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Jest tests + Typescript build
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: tests and build with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: git add .
      - run: git commit -m "tsc build for ${GITHUB_REF#refs/heads/}.${GITHUB_SHA}"
